### ISSUE TITLE
Instructions Error - Building DOCKER IMAGE

### ISSUE THREAD

**Issue by thnguyenf5** [f5devcentral/terraform-nginx-auth#1]
Step 5 of the DOCKER IMAGE build has an incorrect name:

docker tag nginx-oidc ghcr.io/$GITHUB\_USER/nginx-oidc 
docker push ghcr.io/$GITHUB\_USER/nginx-plus-ingress

The last command to docker push is referencing the incorrect image name.  Should read nginx-oidc not nginx-plus-ingress.

**Comment by aknot242** [comment]
Thanks for reporting this!
